service: aws-lambda-typescript
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  deploymentMethod: direct

functions:
  sample:
    handler: ./src/main.sample
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline
